version: '3.1'

services:
  frontend:
    image: node:16.16
    build: site/
    volumes:
      - ./site:/code/site
    command: npm start
    ports:
      - 3000:3000
    depends_on:
      - app

  app:
    image: python:3.10
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "make install_docker && /root/.local/bin/poetry run uvicorn main:app --host 0.0.0.0"
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres
    restart: always
    environment:
# POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      POSTGRES_PASSWORD: quiz
      POSTGRES_USER: quiz
      POSTGRES_DB: quiz
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
