version: '3.1'

services:
  frontend:
    build: site/
    command: npm start
    environment:
      REACT_APP_BASE_URL: ws://83.229.86.43:8000/quiz
    ports:
      - "3000:3000"
    depends_on:
      - python_app

  python_app:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "make install_docker && /root/.local/bin/poetry run uvicorn main:app --host 0.0.0.0"
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: quiz
      POSTGRES_USER: quiz
      POSTGRES_DB: quiz
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
